eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  data:
    mongodb:
      host: seminar-manager-mongodb
      port: 27017
      database: seminar-manager

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/users/current
