eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: seminar-manager

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/users/current
