server:
  port: 8080

zuul:
  routes:
    auth-service:
      path: /uaa/**
      serviceId: auth-service
      sensitiveHeaders:
    seminar-service:
      path: /seminars/**
      serviceId: seminar-service
      sensitiveHeaders:
    speaker-service:
      path: /speakers/**
      serviceId: speaker-service
      sensitiveHeaders:
