server:
  port: 8083

security:
  oauth2:
    client:
      client-id: speaker-service
      client-secret: SPEAKER_SERVICE_PASSWORD
      access-token-uri: http://localhost:5000/oauth/token
      grant-type: client_credentials
      scope: server
