language: java
jdk:
  - oraclejdk8
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # config service
  - export CONFIG=pavzay/seminar-manager-config
  - docker build -t $CONFIG:$TRAVIS_COMMIT ./config-service/
  - docker tag $CONFIG:$TRAVIS_COMMIT $CONFIG:$TAG
  - docker push $CONFIG
