language: java
jdk:
  - oraclejdk8
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # config service
  - export CONFIG=pavzay/seminar-manager-config
  - docker build -t $CONFIG:$TRAVIS_BUILD_NUMBER ./config-service/
  - docker tag $CONFIG:$TRAVIS_BUILD_NUMBER $CONFIG:$TAG
  - docker push $CONFIG

  # discovery service
  - export DISCOVERY=pavzay/seminar-manager-discovery
  - docker build -t $DISCOVERY:$TRAVIS_BUILD_NUMBER ./discovery-service/
  - docker tag $DISCOVERY:$TRAVIS_BUILD_NUMBER $DISCOVERY:$TAG
  - docker push $DISCOVERY

  # gateway service
  - export GATEWAY=pavzay/seminar-manager-gateway
  - docker build -t $GATEWAY:$TRAVIS_BUILD_NUMBER ./gateway-service/
  - docker tag $GATEWAY:$TRAVIS_BUILD_NUMBER $GATEWAY:$TAG
  - docker push $GATEWAY

  # auth service
  - export AUTH=pavzay/seminar-manager-auth
  - docker build -t $AUTH:$TRAVIS_BUILD_NUMBER ./auth-service/
  - docker tag $AUTH:$TRAVIS_BUILD_NUMBER $AUTH:$TAG
  - docker push $AUTH

  # seminar service
  - export SEMINAR=pavzay/seminar-manager-seminar
  - docker build -t $SEMINAR:$TRAVIS_BUILD_NUMBER ./seminar-service/
  - docker tag $SEMINAR:$TRAVIS_BUILD_NUMBER $SEMINAR:$TAG
  - docker push $SEMINAR

  # speaker service
  - export SPEAKER=pavzay/seminar-manager-speaker
  - docker build -t $SPEAKER:$TRAVIS_BUILD_NUMBER ./speaker-service/
  - docker tag $SPEAKER:$TRAVIS_BUILD_NUMBER $SPEAKER:$TAG
  - docker push $SPEAKER
