spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pavzay/seminar-manager
          search-paths: config-service/src/main/resources/config
        native:
          search-locations: classpath:config
server:
  port: 8888

security:
  user:
      name: config
      password: CONFIG_SERVICE_PASSWORD
